### ISSUE TITLE
Setting `initial_context` during behave test configuration

### ISSUE THREAD

**Issue by drmikecrowe** [AlexandreDecan/sismic#103]
I'm trying to setup behave tests for my system.  When I configure my statemachine, I use a pattern such as:

```py
class ActionList:
    A_CHECK_UPGRADE = "A_CHECK_UPGRADE"
    # ...

ACTIONS = {
    "A_CHECK_UPGRADE": ActionList.A_CHECK_UPGRADE,
    # ...
}
TEXT_PHRASES = {
    "TEXT_INTRO": "Press Play to get started",
    # ...
}

# in my main class:
        self.interpreter = Interpreter(
            _statechart, initial_context={**TEXT_PHRASES, **ACTIONS}
        )
```

This allows me to ensure my phrases are correct in my yaml:

```yaml
  root state:
    name: idle
    initial: active
    parallel states:
      - name: active
        initial: waiting
        states:
          - name: waiting
            on entry: |
              send(A_CHECK_UPGRADE)
              send(A_SAY_COMPLETELY, text=TEXT_INTRO)
```

In my `steps.py`, how can I configure the `initial_context` so this pattern works?
