### ISSUE TITLE
Understanding `trace` vs. `monitored_trace` and `on entry`

### ISSUE THREAD

**Issue by drmikecrowe** [AlexandreDecan/sismic#104]
I need to confirm I'm not doing something stupid.  So, here's my "startup" in my definition:

```yaml
  root state:
    name: idle
    initial: active
    on entry: |
      send(A_SAY_COMPLETELY, text='Ready')
    parallel states:
      - name: active
        initial: waiting
        states:
          - name: waiting
            on entry: |
              send(A_CHECK_UPGRADE)
              send(A_SAY_COMPLETELY, text=TEXT_INTRO)
              playing_new_episodes = False
              if playing:
                send(A_PAUSE)
              if update_available:
                send(A_CHECK_UPGRADE)
              refresh_episodes()
```

In writing my first test, I found there wasn't a default step in `bdd` that I needed.  I wrote this as my feature:

```gherkin
  Scenario: Default state is waiting
    Given I do nothing
    When I wait 1 second
    Then variable playing equals False
    And state idle is active
    And event A_SAY_COMPLETELY is consumed with text="Ready"
```

and I wrote the following step:
```py
@then("event {name} is consumed")
@then("event {name} is consumed with {parameter}={value}")
def event_is_consumed(context, name, parameter=None, value=None):
    parameters = {}

    for row in context.table if context.table else []:
        parameters[row["parameter"].strip()] = eval(row["value"].strip(), {}, {})

    if parameter and value:
        parameters[parameter.strip()] = eval(value.strip(), {}, {})

    test = testing.event_is_consumed(context.trace, name, parameters)

    if len(parameters) == 0:
        assert test, "Event {} is not consumed".format(name)
    else:
        assert test, "Event {} is not consumed with parameters {}".format(name, parameters)
```

This works fine, but it worries me I'm immediately trying to do something you're not providing by default.  Am I missing the big picture?
